uestc_sign:
  image: easy12385/uestc_sign
  container_name: uestc_sign
  restart: always
  volumes:
    - ./logs:/uestc_sign/logs
  environment:
    - REPO_URL=https://gitee.com/easyyyyy/uestc_sign.git
    #校园健康填报小程序cookie，多账号用","隔开
    #示例：
    # COOKIE=JSESSIONID=xxx,JSESSIONID=XXX
    - COOKIE=
    #PUSHPLUS
    - PUSH_PLUS_TOKEN=